config/routes.rb
Rails.application.routes.draw do
  resource :users, only: [ :new, :create ]
  resource :session
  resources :passwords, param: :token
  resources :todos, only: [ :index, :new, :create ] do
    resource :completion, only: [ :create ], controller: "todos/completion"
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "todos#index"
end

app/models/todo.rb
# == Schema Information
#
# Table name: todos
#
#  id           :integer          not null, primary key
#  user_id      :integer          not null
#  title        :string
#  description  :text
#  completed_at :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_todos_on_user_id  (user_id)
#

class Todo < ApplicationRecord
  belongs_to :user
  scope :active, -> { where(completed_at: nil) }

  def completed?
    completed_at.present?
  end
end

app/controllers/todos/completion_controller.rb
class Todos::CompletionController < ApplicationController
  def create
    @todo = Todo.find(params[:todo_id])
    @todo.update(completed_at: Time.current)
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  include FunSuggestions

  def index
    @todos = Current.user.todos.active
  end

  def new
    @todo = Todo.new
    load_fun_suggestion
  end

  def create
    @todo = Current.user.todos.create!(todo_params)
    redirect_to todos_url
  end

  private

  def todo_params
    params.require(:todo).permit(:title, :description)
  end
end

app/helpers/todos/completion_helper.rb
module Todos::CompletionHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/index.html.erb
<h1 class="font-bold text-4xl">Todos</h1>
<turbo-frame id="todos">
  <div class="my-3">
    <div class="divide-y-2 divide-y-accent">
      <% @todos.each do |todo| %>
        <%= render TodoComponent.new(todo:) %>
      <% end %>
    </div>
    <turbo-frame id="new-todo">
      <%= link_to "New todo", new_todo_path, class: "btn btn-primary" %>
    </turbo-frame>
  </div>
</turbo-frame>

app/views/todos/new.html.erb
<turbo-frame id="new-todo">
  <%= form_with model: @todo, url: todos_path, data: { turbo_frame: "todos" } do |form| %>
    <div class="my-3">
      <label class="form-control">
        <%= form.text_field :title, class: "input input-bordered input-primary w-full", placeholder: @fun_suggestion[:title_placeholder] %>
        <div class="label">
          <span class="label-text-alt">Title</span>
        </div>
      </label>
    </div>
    <div class="my-3">
      <label class="form-control">
        <%= form.text_area :description, class: "textarea textarea-bordered textarea-primary w-full", placeholder: @fun_suggestion[:description_placeholder] %>
        <div class="label">
          <span class="label-text-alt">Description</span>
        </div>
      </label>
    </div>
    <div class="my-3">
      <%= form.submit "Create todo", class: "btn btn-primary" %>
      <%= link_to "Cancel", todos_path, class: "ml-2 btn btn-secondary" %>
    </div>
  <% end %>
</turbo-frame>